// Settings
export const SET_UNIT = 'SET_UNIT';
export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_TIME_TYPE = 'SET_TIME_TYPE';
export const SET_ACTIVE_LOCATION = 'SET_ACTIVE_LOCATION';

// Locations
export const SET_LOCATION = 'SET_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const ADD_INDEX_LOCATION = 'ADD_INDEX_LOCATION';
export const LOCATION_LOADING = 'LOCATION_LOADING';

// Location Errors
export const ADD_LOCATION_ERROR = 'ADD_LOCATION_ERROR';
export const SET_ACTIVE_LOCATION_ERROR = 'SET_ACTIVE_LOCATION_ERROR';
export const ADD_INDEX_LOCATION_ERROR = 'ADD_INDEX_LOCATION_ERROR';
